### ISSUE TITLE
Timeboxed investigation of BandPlotsWidget issue

### ISSUE THREAD

**Issue by unkcpz** [osscar-org/widget-bandsplot#49]
The issue manifested in QeApp, as shown in the figure below, the dos diagram has a small jump. 
If possible the background gray filling of total dos shows only fill the dos below the fermi energy.

![image](https://user-images.githubusercontent.com/8831685/219082767-09668bac-6149-4168-876d-785d76dc1855.png)

**Comment by unkcpz** [comment]
Hi @dou-du, any update on this issue? I remember you mentioned in the meeting that can not access THEOS AiiDAlab server to reproduce the issue. Do you need any help?

**Comment by dou-du** [comment]
> Hi @dou-du, any update on this issue? I remember you mentioned in the meeting that can not access THEOS AiiDAlab server to reproduce the issue. Do you need any help?

Thanks! I will come back to you later today. I will try to install aiidalab locally and see the result.

**Comment by dou-du** [comment]
![image](https://user-images.githubusercontent.com/56022756/221555436-f5811802-646b-4811-b3cf-ed04f0eec10b.png)

Indeed, the issue is exsiting. I will try to solve it as soon as possible.

**Comment by dou-du** [comment]
Some updates:

![image](https://user-images.githubusercontent.com/56022756/221786429-5848ada8-2a9a-4774-b386-c9f38ceace62.png)

The issue is not related to Fermi line. And only showing in the vertical plotting. There is no problme for the horizational DOS plot.

It may be a issue from chart.js. However, our chart.js is version is too low. It is urgent to upgrade the chart.js version to 4.x.

**Comment by dou-du** [comment]
PR #56 to fix this issue.



![Image](https://user-images.githubusercontent.com/56022756/225555816-cfae5bbd-a6a9-4d64-8ab7-1fe388716720.png)
