### ISSUE TITLE
Task to improve the widget-bandsplot

### ISSUE THREAD

**Issue by dou-du** [osscar-org/widget-bandsplot#7]
Please give some comments to finalize the widget, for example, the missing functions (spin up and down side by side for the DOS), bugs (color issue for the band structure) and  labels.

**Comment by unkcpz** [comment]
@mbercx and I had a quick discussion offline and summarize issues that can work on first.

- spin up and down side by side for the DOS as already list by @dou-du 
- dos bug that for some structures (Au4 for example) the scale of dos plot is very small.  I think this is caused by that out of the setting y range there are large density states.
- [New feature request] I can set multiple bands to inputs but the bands are not able to be distinguished. The automatically multi bands colored should only work for bands instead of for dos plot since we already have pdos distinguished by color.
